---
- name: "prem : config : Generate infrastructure config file {{ r_infra_dir_conf }}/{{ r_infra_config_file }}"
  template:
    src: templates/libre-infra.j2
    dest: "{{ r_infra_dir_conf }}/{{ r_infra_config_file }}"
    mode: 0664
    owner: "{{ r_session_user }}"
    group: "{{ r_session_group }}"
  become: yes
- name: "prem : config : Succesfull config for On-Premise infrastructure"
  debug:
    msg:
      - " "
      - "On-Premise infrastructure for session {{ libre_session.id }} delivering course {{ libre_session.course }}"
      - "is now configured. You can continue this process by :"
      - " "
      - "1. Review classroom infrastructure configuration file {{r_infra_dir_conf}}/{{ r_infra_config_file }}"
      - "2. Start provisionning infrastructure by executing the following command :"
      - "   $ libre-infra prem provision"
      - " "
      - " Have an happy training ;)"
      - " "
