---
- name: "prem : provision : Install TFTP packages"
  yum:
    name:
    - tftp
    - tftp-server*
    - xinetd*
- name: "prem : provision : Enable service tftp"
  systemd:
    name: tftp
    enabled: yes
    state: started 
- name: "prem : provision : Enable service xinetd"
  systemd:
    name: xinetd
    enabled: yes
    state: started 

- name: "prem : provision : TODO !!!"
  debug:
    msg: "prem : provision : TODO !!!"
