---
- name: "install-postcheck : Training directory detail must exist"
  assert:
    msg: "Training directory details don't exist. Try to re-install LIBRE Toolkit and start this setup again."
    that: r_libre_dir_details is defined
