---
# Install pre-tasks
- name: "install : Start instructor pre-installation checks"
  include_tasks: install-precheck.yml
  when: not libre_instructor_install_precheck or
            libre_instructor_install_precheck is undefined

# Install tasks
- name: "install : Start repository install"
  include_role:
    name: repository
    tasks_from: install

- name: "install : Get previous report data"
  set_fact:
    previous_report: "{{ lookup('file', r_libre_tmp + '/' + r_libre_tmpfile) }}"
  delegate_to: localhost

- name: "install : Generate LIBRE report at {{ r_libre_tmp }}/{{ r_libre_tmpfile }}"
  template:
    src: libre_report-install.j2
    dest: "{{ r_libre_tmp }}/{{ r_libre_tmpfile }}"
    mode: 0664
  delegate_to: localhost

- name: "install : Log install action"
  include_role:
    name: libre
    tasks_from: lib/log
  vars:
    log_name: "Instructor workstation is installed"
    log_component: instructor
    log_action: install

# Install post-tasks
- name: "install : Start instructor post-installation checks"
  include_tasks: install-postcheck.yml
