---
- name: "self : config : Generate ssh keypairs in {{config_libre.directory.conf}}"
  openssh_keypair:
    path: "{{config_libre.directory.conf}}/{{ user2 }}-id_rsa"
    size: 4096
    type: rsa
    owner: "{{ r_libre_user }}"
    group: "{{ r_libre_group }}"
  loop:
    - infra
    - instructor
    - student
  loop_control:
    loop_var: user2
- name: "self : config : Generate infrastructure config file {{ config_libre.directory.conf }}/{{ r_infra_config_file }}"
  template:
    src: templates/libre-infra.j2
    dest: "{{ config_libre.directory.conf }}/{{ r_infra_config_file }}"
    mode: 0664
    owner: "{{ r_libre_user }}"
    group: "{{ r_libre_group }}"
- name: "self : config : Succesfull config for Self-Hosted infrastructure"
  debug:
    msg:
      - " "
      - "Self-Hosted infrastructure for session {{ libre_session.id }} delivering course {{ libre_session.course }}"
      - "is now configured. You can continue this process by :"
      - " "
      - "1. Review classroom infrastructure configuration file {{config_libre.directory.conf}}/{{ r_infra_config_file }}"
      - "2. Start provisionning infrastructure by executing the following command :"
      - "   $ libre-infra self provision"
      - " "
      - " Have an happy training ;)"
      - " "
