---
- name: "self : provision-post : Update /etc/hosts file"
  blockinfile:
    dest: /etc/hosts
    content: "{{ libre_infra.network.associated_ip }}       localhost.localdomain localhost instructor.{{libre_infra.network.dns}} student.{{libre_infra.network.dns}}"
    state: present
- name: "self : provision-post : Create the libre user group"
  group:
    name: "{{ r_infra_usergroup }}"
    state: present
- name: "self : provision-post : Create the instructor user"
  user:
    state: present
    name: "{{ r_infra_user_instructor }}"
    comment: "LIBRE {{ r_infra_user_instructor }}"
    group: "{{ r_infra_usergroup }}"
- name: "self : provision-post : Create the student user"
  user:
    state: present
    name: "{{ r_infra_user_student }}"
    comment: "LIBRE {{ r_infra_user_student }}"
    group: "{{ r_infra_usergroup }}"
- name: "self : provision-post : Authorize infrastructure SSH key"
  authorized_key:
    user: "{{ user1 }}"
    state: present
    key: "{{ lookup('file', config_libre.directory.conf + '/infra-id_rsa.pub') }}"
  loop:
    - root
    - "{{ r_infra_user_instructor }}"
    - "{{ r_infra_user_student }}"
  loop_control:
    loop_var: user1
- name: "self : provision-post : Authorize instructor SSH key"
  authorized_key:
    user: "{{ user2 }}"
    state: present
    key: "{{ lookup('file', config_libre.directory.conf + '/instructor-id_rsa.pub') }}"
  loop:
    - root
    - "{{ r_infra_user_instructor }}"
    - "{{ r_infra_user_student }}"
  loop_control:
    loop_var: user2
- name: "self : provision-post : Authorize student SSH key"
  authorized_key:
    user: "{{ r_infra_user_student }}"
    state: present
    key: "{{ lookup('file', config_libre.directory.conf + '/student-id_rsa.pub') }}"
- name: "self : provision-post : Ensure SSH private and public key are present"
  copy:
    src: "{{ config_libre.directory.conf }}/{{keyf.key}}"
    dest: "{{keyf.dir}}/.ssh/{{keyf.key}}"
    mode: 0600
    owner: "{{keyf.user}}"
    group: "{{ r_infra_usergroup }}"
  loop:
    - user: root
      key: infra-id_rsa.pub
      dir: "/root/"
    - user: root
      key: infra-id_rsa
      dir: "/root/"
    - user: "{{ r_infra_user_instructor }}"
      key: instructor-id_rsa.pub
      dir: "/home/{{ r_infra_user_instructor }}"
    - user: "{{ r_infra_user_instructor }}"
      key: instructor-id_rsa
      dir: "/home/{{ r_infra_user_instructor }}"
    - user: "{{ r_infra_user_student }}"
      key: student-id_rsa.pub
      dir: "/home/{{ r_infra_user_student }}"
    - user: "{{ r_infra_user_student }}"
      key: student-id_rsa
      dir: "/home/{{ r_infra_user_student }}"
  loop_control:
    loop_var: keyf
- name: "self : provision-post : Change hostname for students"
  hostname:
    name: "{{ inventory_hostname }}"
  become: yes
  when: inventory_hostname in groups.students
- name: "self : provision-post : Change hostname for instructor"
  hostname:
    name: "{{ inventory_hostname }}"
  become: yes
  when: inventory_hostname in groups.instructor

- name: "self : provision-post : Set infrastructure state to provisionned"
  set_fact:
    libre_infra: "{{ libre_infra|combine({'state': 'post-provisionned' }, recursive=True) }}"
- name: "self : provision-post : Update infrastructure config file {{ config_libre.directory.conf }}/{{ r_infra_config_file }}"
  template:
    src: templates/libre-infra.j2
    dest: "{{ config_libre.directory.conf }}/{{ r_infra_config_file }}"
- name: "self : provision-post : Get previous report data"
  set_fact:
    previous_report: "{{ lookup('file', r_libre_tmp + '/' + r_libre_tmpfile) | default('') }}"
  run_once: true
- name: "self : provision-post : Generate LIBRE report at {{ r_libre_tmp }}/{{ r_libre_tmpfile }}"
  template:
    src: templates/libre_report-provision-post.j2
    dest: "{{ r_libre_tmp }}/{{ r_libre_tmpfile }}"
    mode: 0664
  run_once: true
- name: "self : provision-post : Log post-provision action"
  include_role:
    name: libre
    tasks_from: lib/log
  vars:
    log_name: "Self-Hosted infrastructure is Post-provisionned"
    log_component: infra-self
    log_action: post-provision
  run_once: true
- name: "self : provision-post : Post-provisionning is finish"
  debug:
    msg:
      - "We are happy to report that self-hosted infrastructure {{ libre_session.id }} for course {{ libre_session.course }} was successfully post-provisioned on Self-Hosted infrastructure"
      - " "
      - "Here are some interesting characteristics of this infrastructure:"
      - " "
      - "  - Instructor: instructor.{{ libre_infra.network.dns }}"
      - "  - Student   : student.{{ libre_infra.network.dns }}"
      - "  - IP address: {{ libre_infra.network.associated_ip }}"
      - " "
      - "You can continue this process by running the following command :"
      - "   $ libre-session start "
      - " "
      - " Have an happy training ;)"
  run_once: true
