---
- name: "aws : config : Configure AWS access key"
  pause:
   prompt: "What is your AWS Access key ?"
  register: aws_access_key
- name: "aws : config : Register access_key in libre_infra fact"
  set_fact:
    libre_infra: "{{ libre_infra|combine({'auth': {'access_key': aws_access_key.user_input }}, recursive=True) }}"
  when: aws_access_key.user_input is defined
- name: "aws : config : Configure AWS access key"
  pause:
   prompt: "What is your AWS Access key ?"
  register: aws_secret_key
- name: "aws : config : Register secret_key in libre_infra fact"
  set_fact:
    libre_infra: "{{ libre_infra|combine({'auth': {'secret_key': aws_secret_key.user_input }}, recursive=True) }}"
  when: aws_secret_key.user_input is defined

- name: "aws : config : Generate infrastructure config file {{ config_libre.directory.conf }}/{{ r_infra_config_file }}"
  template:
    src: templates/libre-infra.j2
    dest: "{{ config_libre.directory.conf }}/{{ r_infra_config_file }}"
    mode: 0664
    owner: "{{ r_libre_user }}"
    group: "{{ r_libre_group }}"
  become: yes
- name: "aws : config : Succesfull config for Public-Cloud AWS infrastructure"
  debug:
    msg:
      - " "
      - "Public-Cloud AWS infrastructure for session {{ libre_session.id }} delivering course {{ libre_session.course }}"
      - "is now configured. You can continue this process by :"
      - " "
      - "1. Review classroom infrastructure configuration file {{config_libre.directory.conf}}/{{ r_infra_config_file }}"
      - "2. Start provisionning infrastructure by executing the following command :"
      - "   $ libre-infra aws provision"
      - " "
      - " Have an happy training ;)"
      - " "
