---
- name: "aws : provision-post : Create the libre user group on all workstations"
  group:
    name: "{{ r_infra_usergroup }}"
    state: present
  become: yes
- name: "aws : provision-post : Create the instructor user on all workstations"
  user:
    state: present
    name: "{{ r_infra_user_instructor }}"
    comment: "LIBRE {{ r_infra_user_instructor }}"
    group: "{{ r_infra_usergroup }}"
  become: yes
- name: "aws : provision-post : Create the student user on all students workstations"
  user:
    state: present
    name: "{{ r_infra_user_student }}"
    comment: "LIBRE {{ r_infra_user_student }}"
    group: "{{ r_infra_usergroup }}"
  become: yes
  when: inventory_hostname in groups.students

- name: "aws : provision-post : Copy ssh default private key {{r_libre_userconfig_dir}}/infra-id_rsa to {{ config_libre.directory.conf }}/infra-id_rsa"
  copy:
    src: "{{r_libre_userconfig_dir}}/infra-id_rsa"
    dest: "{{ config_libre.directory.conf }}/infra-id_rsa"
    mode: 0644
  when: libre_infra_ssh_private_key_file is defined
- name: "aws : provision-post : Copy ssh default public key {{r_libre_userconfig_dir}}/infra-id_rsa.pub to {{ config_libre.directory.conf }}/infra-id_rsa"
  copy:
    src: "{{r_libre_userconfig_dir}}/infra-id_rsa.pub"
    dest: "{{ config_libre.directory.conf }}/infra-id_rsa.pub"
    mode: 0644
- name: "aws : provision-post : Authorize infrastructure SSH key"
  authorized_key:
    user: "{{ user1 }}"
    state: present
    key: "{{ lookup('file', config_libre.directory.conf + '/infra-id_rsa.pub') }}"
  loop:
    - root
    - "{{ libre_infra.ssh.user }}"
    - "{{ r_infra_user_instructor }}"
    - "{{ r_infra_user_student }}"
  loop_control:
    loop_var: user1
- name: "aws : provision-post : Authorize instructor SSH key"
  authorized_key:
    user: "{{ user2 }}"
    state: present
    key: "{{ lookup('file', config_libre.directory.conf + '/instructor-id_rsa.pub') }}"
  loop:
    - root
    - "{{ libre_infra.ssh.user }}"
    - "{{ r_infra_user_instructor }}"
    - "{{ r_infra_user_student }}"
  loop_control:
    loop_var: user2
- name: "aws : provision-post : Authorize student SSH key"
  authorized_key:
    user: "{{ user3 }}"
    state: present
    key: "{{ lookup('file', config_libre.directory.conf + '/student-id_rsa.pub') }}"
  loop:
    - "{{ libre_infra.ssh.user }}"
    - "{{ r_infra_user_student }}"
  loop_control:
    loop_var: user3
- name: "aws : provision-post : Ensure Student SSH private and public key are present"
  copy:
    src: "{{ config_libre.directory.conf }}/{{keyf.key}}"
    dest: "{{keyf.dir}}/.ssh/{{keyf.key}}"
    mode: 0600
    owner: "{{keyf.user}}"
    group: "{{ r_infra_usergroup }}"
  loop:
    - user: "{{ r_infra_user_student }}"
      key: student-id_rsa.pub
      dir: "/home/{{ r_infra_user_student }}"
    - user: "{{ r_infra_user_student }}"
      key: student-id_rsa
      dir: "/home/{{ r_infra_user_student }}"
  loop_control:
    loop_var: keyf
- name: "aws : provision-post : Change hostname for students"
  hostname:
    name: "{{ inventory_hostname }}"
  become: yes
  when: inventory_hostname in groups.students
- name: "aws : provision-post : Change hostname for instructor"
  hostname:
    name: "{{ inventory_hostname }}"
  become: yes
  when: inventory_hostname in groups.instructor

- name: "aws : provision-post : Set infrastructure state to provisionned"
  set_fact:
    libre_infra: "{{ libre_infra|combine({'state': 'post-provisionned' }, recursive=True) }}"
- name: "aws : provision-post : Update infrastructure config file {{ config_libre.directory.conf }}/{{ r_infra_config_file }}"
  template:
    src: templates/libre-infra.j2
    dest: "{{ config_libre.directory.conf }}/{{ r_infra_config_file }}"
  become: yes
- name: "aws : provision-post : Get previous report data"
  set_fact:
    previous_report: "{{ lookup('file', r_libre_tmp + '/' + r_libre_tmpfile) | default('') }}"
- name: "aws : provision-post : Generate LIBRE report at {{ r_libre_tmp }}/{{ r_libre_tmpfile }}"
  template:
    src: templates/libre_report-provision-post.j2
    dest: "{{ r_libre_tmp }}/{{ r_libre_tmpfile }}"
    mode: 0664
- name: "aws : provision-post : Log post-provision action"
  include_role:
    name: libre
    tasks_from: lib/log
  vars:
    log_name: "AWS infrastructure is Post-provisionned"
    log_component: infra-aws
    log_action: post-provision
- name: "aws : provision-post : Post-provisionning is finish"
  debug:
    msg:
      - " "
      - "We are happy to report that AWS infrastructure {{ libre_session.course }}.{{ libre_infra.route53.domain }} was successfully provisioned on AWS infrastructure"
      - " "
      - "You can now connect to your instructor workstation :"
      - "  ssh -i {{ libre_infra.ssh.keyname }}.pem {{ libre_infra.ssh.user }}@instructor.{{ libre_session.course }}.{{ libre_infra.route53.domain }}"
      - "Then run instructor installation by running :"
      - "  libre-instructor install"
      - " "
      - " Have a happy setup ;)"
  run_once: true
