---
- name: "aws : provision-post-post : student {{ student.id}} : Change hostname for student nodes"
  hostname:
    name: "{{node.name}}{{student.workstation|default('0')}}"
  become: yes
  delegate_to: "{{node.name}}-env{{student.workstation|default('0')}}.{{ libre_session.id }}.{{ libre_infra.route53.domain }}"
  loop: "{{ classroom }}"
  loop_control:
    loop_var: node
    label: "{{ node.name }}"
- name: "aws : provision-post-post : student {{ student.id}} : Update student /etc/hosts file"
  copy:
    src: /tmp/{{student.workstation|default('0')}}.hosts
    dest: /etc/hosts
  become: yes
  delegate_to: "{{node.name}}-env{{student.workstation|default('0')}}.{{ libre_session.id }}.{{ libre_infra.route53.domain }}"
  loop: "{{ classroom }}"
  loop_control:
    loop_var: node
    label: "{{ node.name }}"
- name: "aws : provision-post-post : student {{ student.id}} : Copy session {{ libre_session.id }} configuration to workstation"
  copy:
    src: "{{ config_libre.directory.conf }}/{{ r_session_config_file }}"
    dest: "{{ config_libre.directory.conf }}/{{ r_session_config_file }}"
    owner: "{{ r_libre_user }}"
    group: "{{ r_libre_group }}"
  delegate_to: "workstation-env{{student.workstation|default('0')}}.{{ libre_session.id }}.{{ libre_infra.route53.domain }}"
- name: "aws : provision-post-post : student {{ student.id}} : Copy course {{ libre_session.course }} manifest to workstation"
  copy:
    src: "{{ r_session_dir_course }}/manifest.yml"
    dest: "{{ r_session_dir_course }}/manifest.yml"
    owner: "{{ r_libre_user }}"
    group: "{{ r_libre_group }}"
  delegate_to: "workstation-env{{student.workstation|default('0')}}.{{ libre_session.id }}.{{ libre_infra.route53.domain }}"
- name: "aws : provision-post-post : student {{ student.id}} : Create course {{ libre_session.course }} playbook directory to workstation"
  file:
    path: "{{ r_session_dir_course }}/playbooks/labs"
    state: directory
    recurse: yes
    owner: "{{ r_libre_user }}"
    group: "{{ r_libre_group }}"
  delegate_to: "workstation-env{{student.workstation|default('0')}}.{{ libre_session.id }}.{{ libre_infra.route53.domain }}"
- name: "aws : provision-post-post : student {{ student.id}} : Copy course {{ libre_session.course }} playbooks archive to workstation"
  unarchive:
    src: "/tmp/playbooks-labs.tgz"
    dest: "{{ r_session_dir_course }}/playbooks/labs"
    owner: "{{ r_libre_user }}"
    group: "{{ r_libre_group }}"
  delegate_to: "workstation-env{{student.workstation|default('0')}}.{{ libre_session.id }}.{{ libre_infra.route53.domain }}"
- name: "aws : provision-post-post : student {{ student.id}} : Add infrastructure inventory {{config_libre.directory.conf}}/inventory in workstation"
  file:
    state: "directory"
    path: "{{config_libre.directory.conf}}/inventory"
  delegate_to: "workstation-env{{student.workstation|default('0')}}.{{ libre_session.id }}.{{ libre_infra.route53.domain }}"
- name: "aws : provision-post-post : student {{ student.id}} : Generate students inventory {{config_libre.directory.conf}}/inventory/students.yml"
  template:
    src: "../templates/inventory-student.j2"
    dest: "{{ config_libre.directory.conf }}/inventory/students.yml"
    mode: 0664
    owner: "{{ r_libre_user }}"
    group: "{{ r_libre_group }}"
  delegate_to: "workstation-env{{student.workstation|default('0')}}.{{ libre_session.id }}.{{ libre_infra.route53.domain }}"
