---
- name: "Configure instructor environment on instructor"
  hosts: 'instructor'
  gather_facts: true

  roles:
    - { role: instructor, do: load }
    - { role: session, do: config, become: yes }
    - { role: infra, do: config, become: yes }
