---
- name: "uninstall : libre : Remove libre-* library from {{ r_libre_dest_lib }}"
  file:
    state: absent
    path: "{{ r_libre_dest_lib }}/{{ libname }}"
  loop: "{{ r_libre_files_library }}"
  loop_control:
    loop_var: libname

- name: "uninstall : libre : Remove libre-* binary from {{ r_libre_dest_bin }}"
  file:
    state: absent
    path: "{{ r_libre_dest_bin }}/{{ binname }}"
  loop: "{{ r_libre_files_binary_all }}"
  loop_control:
    loop_var: binname

- name: "uninstall : libre : Remove libre ansible library from {{ r_libre_dest_ansible }}"
  file:
    state: absent
    path: "{{ r_libre_dest_ansible }}"

- name: "uninstall : libre : Remove auto-completion script to /etc/bash_completion.d/libre"
  file:
    state: absent
    path: /etc/bash_completion.d/libre
