---
- name: "uninstall_user : Remove the instructor user {{ r_libre_user }}"
  user:
    state: absent
    name: "{{ r_libre_user }}"
    remove: yes
    force: yes
- name: "uninstall_user : Remove the libre user group {{ r_libre_group }}"
  group:
    name: "{{ r_libre_group }}"
    state: absent
