---
# Start pre-tasks
- name: "list : Course description is loaded"
  assert:
    msg: "Course description {{ r_session_dir_course }}/manifest.yml is not loaded"
    that: libre_course is defined

# Start tasks
- name: "list : Get previous report data"
  set_fact:
    previous_report: "{{ lookup('file', r_libre_tmp + '/' + r_libre_tmpfile) | default('') }}"
  delegate_to: localhost
- name: "list : Generate LIBRE report at {{ r_libre_tmp }}/{{ r_libre_tmpfile }}"
  template:
    src: templates/libre_report-list.j2
    dest: "{{ r_libre_tmp }}/{{ r_libre_tmpfile }}"
    mode: 0664
  delegate_to: localhost
