---
# Start pre-tasks
- name: "start : Course description is loaded"
  assert:
    msg: "Course description {{ r_session_dir_course }}/manifest.yml is not loaded"
    that: libre_course is defined
- name: "start : Current chapter is defined"
  assert:
    msg: "Current chapter is not defined"
    that: chapter_current is defined

# Start tasks
- name: "start : Generate current chapter tracker on {{ config_libre.directory.conf }}/{{ r_chapter_config_current }}"
  template:
    src: chapter-current.j2
    dest: "{{ config_libre.directory.conf }}/{{ r_chapter_config_current }}"
    mode: 0664
    owner: "{{ r_libre_user }}"
    group: "{{ r_libre_group }}"
  become: yes
- name: "start : Get previous report data"
  set_fact:
    previous_report: "{{ lookup('file', r_libre_tmp + '/' + r_libre_tmpfile) | default('') }}"
  delegate_to: localhost
- name: "start : Generate LIBRE report at {{ r_libre_tmp }}/{{ r_libre_tmpfile }}"
  template:
    src: libre_report-start.j2
    dest: "{{ r_libre_tmp }}/{{ r_libre_tmpfile }}"
    mode: 0664
  delegate_to: localhost
- name: "start : Log start action"
  include_role:
    name: libre
    tasks_from: lib/log
  vars:
    log_name: "Started chapter {{ libre_chapter.id }} : {{ libre_chapter.name }}"
    log_component: chapter
    log_action: start
