- include_vars: grade_vars.yml

- name: Check if 1 is greter than 0 or not
  set_fact:
    test2: True
  when: 1 > 0

- include_tasks: print.yml
  vars:
    msg: Verify the TEST N°1
    success: "{{ test1 }}"

- include_tasks: print.yml
  vars:
    msg: Verify the TEST N°2
    success: "{{ test2 }}"