- become: yes
  block:
    - name: Create the /home/student/{{ current_lab.idn }} directory for the lab
      file:
        path: /home/student/{{ current_lab.idn }}
        state: directory
        owner: student
        group: student
        mode: 0755

    - name: Copy files to /home/student/{{ current_lab.idn }} directory
      loop: [ansible.cfg, inventory]
      copy:
        src: files/{{ item }}
        dest: /home/student/{{ current_lab.idn }}
        owner: student
        group: student
        mode: 0644