---
# Install pre-tasks
- name: "install : Start student pre-installation checks"
  include_tasks: "install-precheck.yml"
  when: libre_student_install_precheck is undefined or libre_student_install_precheck != true

# Install tasks
- name: "install : Start LIBRE install"
  include_role:
    name: libre
    tasks_from: install
  become: yes
- name: "install : Get previous report data"
  set_fact:
    previous_report: "{{ lookup('file', r_libre_tmp + '/' + libre_tmpfile) | default('') }}"
  delegate_to: localhost
- name: "install : Generate LIBRE report at {{ r_libre_tmp }}/{{ libre_tmpfile }}"
  template:
    src: templates/libre_report-install.j2
    dest: "{{ r_libre_tmp }}/{{ libre_tmpfile }}"
    mode: 0664
  delegate_to: localhost
- name: "install : Log install action"
  include_role:
    name: libre
    tasks_from: lib/log
  vars:
    log_name: "Student workstation is installed"
    log_component: student
    log_action: install

# Install post-tasks
- name: "install : Start student post-installation checks"
  include_tasks: "install-postcheck.yml"
