---
- name: "install-precheck : Start repository pre-installation checks"
  include_role:
    name: repository
    tasks_from: "install-precheck.yml"
  when: session_install_precheck is undefined or session_install_precheck != true
- name: "install-precheck : Mark session install-precheck as done"
  set_fact: session_install_precheck=true