---
- when: not session_install_postcheck or
            session_install_postcheck is undefined
  block:
  - name: "install-postcheck : Session configuration file {{ r_session_config_file }} exists"
    assert:
      that: r_session_conf_details.stat.exists
      msg: |

        Session configuration file {{ r_session_config_file }} doesn't exist

        You can configure session with the following command :
        $ libre-session install

  - name: "install-postcheck : Training configuration {{ r_session_config_file }} is loaded"
    assert:
      that: libre_session is defined
      msg: "Session configuration file {{ r_session_config_file }} is not loaded"

  - name: "install-postcheck : Check if session id exists"
    assert:
      that: libre_session.id is defined
      msg: |

        Session ID must be defined in {{ r_session_config_file }}

        You can configure session with the following command :
        $ libre-session install

  - name: "install-postcheck : Check if course id exists"
    assert:
      that: libre_session.course is defined
      msg: |

        Session course must be defined in {{ r_session_config_file }}

        You can configure session with the following command :
        $ libre-session install

  - name: "install-postcheck : Course manifest exists in {{ config_libre.directory.course }}"
    assert:
      that: r_course_manifest_details.stat.exists
      msg: "Course manifest not found in {{ config_libre.directory.course }}"

- name: "install-postcheck : Mark session install-postcheck as done"
  set_fact:
    session_install_postcheck: True
