---
# Uninstall pre-tasks
- name: "uninstall : Uninstall course playbook"
  include_tasks: "{{ r_session_dir_course }}/{{ r_session_dir_course_playbooks}}/uninstall.yml"
  when: r_session_dir_course_playbooks_details.stat.exists == true

# Uninstall tasks
- name: "uninstall : Start repository uninstall"
  include_role:
    name: repository
    tasks_from: uninstall
  become: yes
- name: "uninstall : Test if course directory directory exist"
  stat:
    path: "{{ r_session_dir_course }}/manifest.yml"
  register: training_dir_details
- name: "uninstall : Remove course directory content {{ r_session_dir_course }}"
  file:
    state: absent
    path: "{{ r_session_dir_course }}/"
  when: training_dir_details.stat.exists == true
- name: "uninstall : Get previous report data"
  set_fact:
    previous_report: "{{ lookup('file', r_libre_tmp + '/' + r_libre_tmpfile) | default('') }}"
  delegate_to: localhost
- name: "uninstall : Generate LIBRE report at {{ r_libre_tmp }}/{{ r_libre_tmpfile }}"
  template:
    src: templates/libre_report-uninstall.j2
    dest: "{{ r_libre_tmp }}/{{ r_libre_tmpfile }}"
    mode: 0664
  delegate_to: localhost
- name: "uninstall : Log uninstall action"
  include_role:
    name: libre
    tasks_from: lib/log
  vars:
    log_name: "Session is uninstalled"
    log_component: session
    log_action: uninstall
