---
# Install pre-tasks
- name: "install : Start LIBRE pre-installation checks"
  include_tasks: install-precheck.yml
  when: not libre_install_precheck or
            libre_install_precheck is undefined

# Install tasks
- name: "install : Start LIBRE installation"
  include_tasks: install/{{ item }}.yml
  with_items:
    - services
    - libre
    - user
    - directory
    - homedir
    - config
    - hardware
    - inventory

- stat: path="{{r_libre_tmp + '/' + r_libre_tmpfile}}"
- stat: path="{{r_libre_tmp + '/' + r_libre_tmpfile}}"
  delegate_to: localhost
- name: "install : Get previous report data"
  set_fact:
    previous_report: "{{ lookup('file', r_libre_tmp + '/' + r_libre_tmpfile) }}"
  become: no
  delegate_to: localhost
- name: "install : Generate LIBRE report at {{ r_libre_tmp }}/{{ r_libre_tmpfile }}"
  template:
    src: libre_report-install.j2
    dest: "{{ r_libre_tmp }}/{{ r_libre_tmpfile }}"
    mode: 0664
  become: no

# Install post-tasks
- name: "install : Start LIBRE post-installation checks"
  include_tasks: install-postcheck.yml
