---
## LIBRE role tasks
- name: "Action {{ r_do }} in LIBRE role is supported"
  assert:
    msg: "Action {{ r_do }} in LIBRE role is not supported"
    that: >
      r_do in [
               'load',
               'status',
               'install',
               'upgrade',
               'uninstall',
              ]

- name: "{{ r_do }} LIBRE environment"
  include_tasks: "{{ r_do }}.yml"
