---
# - name: "lab : start (pre) : Copy the lab inventory if it exists"
#   block:
#     - name: "lab : start (pre) : {{ r_current_lab_dir }} directory details"
#       stat:
#         path: "{{ r_current_lab_dir }}/inventory"
#       register: r_lab_inventory_status
#     - name: "lab : start (pre) : Copy {{ r_current_lab_dir }}/inventory to {{config_libre.directory.conf}}/inventory/lab"
#       when: r_lab_inventory_status.stat.exists
#       copy: 
#         remote_src: yes
#         src: "{{ r_current_lab_dir }}/inventory"
#         dest: "{{config_libre.directory.conf}}/inventory/lab"
#     - name: "lab : start (pre) : Reload the inventory"
#       meta: refresh_inventory

- name: "lab : {{ lab_action }} : Create symlink from {{ r_current_lab_dir }} to /tmp/current_lab"
  file:
    src: "{{ r_current_lab_dir }}"
    dest: /tmp/current_lab
    owner: student
    group: "{{ r_libre_group }}"
#    mode: '0700'
    state: link
    force: yes

- name: "lab : {{ lab_action }} : Create symlink from {{ r_libre_tmp }}/{{ r_libre_tmpfile }} to {{ r_current_lab_dir }}/output.txt"
  file:
    src: "{{ r_libre_tmp }}/{{ r_libre_tmpfile }}"
    dest: "{{ r_current_lab_dir }}/output.txt"
    owner: student
    group: "{{ r_libre_group }}"
    mode: '0644'
    state: link
    force: yes

- name: "lab : {{ lab_action }} : Copy lab manifest part to {{ r_current_lab_dir }}/manifest.yml"
  block:
  - stat:
      path: "{{ r_current_lab_dir }}/manifest.yml"
    register: r_current_lab_manifest_status

  - copy:
      content: "{{ r_current_lab_manifest | to_nice_yaml }}"
      dest: "{{ r_current_lab_dir }}/manifest.yml"
    vars:
      r_current_lab_manifest:
        current_lab: "{{ current_lab }}"
    when: not r_current_lab_manifest_status.stat.exists