---
- name: "load_config : Load user libre configuration from {{ r_libre_userconfig_dir }}/{{ r_libre_myconfile_libre }}"
  set_fact:
    config_libre: "{{ lookup('file', r_libre_userconfig_dir + '/' + r_libre_myconfile_libre, errors='ignore') | from_yaml }}"
  become: no
- name: "load_config : Load default user libre configuration"
  set_fact:
    config_libre: "{{ r_libre_libre_userconf_default }}"
  when: config_libre == ''
