---
- name: "install_directory : Create training configuration directory {{ r_libre_dir_conf }}"
  file:
    state: directory
    path: "{{ r_libre_dir_conf }}"
    mode: 0775
    owner: "{{ r_libre_user }}"
    group: "{{ r_libre_group }}"
    recurse: yes
  when: r_libre_dir_conf_details.stat.exists != true
- name: "install_directory : Reload {{ r_libre_dir_conf }} directory details"
  stat:
    path: "{{ r_libre_dir_conf }}"
  register: r_libre_dir_conf_details
- name: "install_directory : Create training directory {{ r_libre_dir }}"
  file:
    state: directory
    path: "{{ r_libre_dir }}"
    mode: 0775
    owner: "{{ r_libre_user }}"
    group: "{{ r_libre_group }}"
    recurse: yes
  when: r_libre_dir_details.stat.exists != true
- name: "install_directory : Reload {{ r_libre_dir }} directory details"
  stat:
    path: "{{ r_libre_dir }}"
  register: r_libre_dir_details
- name: "install_directory : Create training course directory {{ r_libre_dir_course }}"
  file:
    state: directory
    path: "{{ r_libre_dir_course }}"
    mode: 0775
    owner: "{{ r_libre_user }}"
    group: "{{ r_libre_group }}"
    recurse: yes
  when: r_libre_dir_course_details.stat.exists != true
- name: "install_directory : Reload {{ r_libre_dir_course }} directory details"
  stat:
    path: "{{ r_libre_dir_course }}"
  register: r_libre_dir_course_details
- name: "install_directory : Get {{ r_libre_dir_collect }} directory details"
  stat:
    path: "{{ r_libre_dir_collect }}"
  register: r_libre_dir_collect_details
- name: "install_directory : Create training collect directory {{ r_libre_dir_collect }}"
  file:
    state: directory
    path: "{{ r_libre_dir_collect }}"
    mode: 0775
    owner: "{{ r_libre_user }}"
    group: "{{ r_libre_group }}"
    recurse: yes
  when: r_libre_dir_collect_details.stat.exists != true
- name: "install_directory : Get {{ r_libre_dir_collect }}/log.yml file details"
  stat:
    path: "{{ r_libre_dir_collect }}/log.yml"
  register: r_libre_dir_collect_log_details
- name: "install_directory : Ensure log file {{ r_libre_dir_collect }}/log.yml exist"
  copy:
    content: ""
    dest: "{{ r_libre_dir_collect }}/log.yml"
    remote_src: yes
    force: no
    mode: 0664
    owner: "{{ r_libre_user }}"
    group: "{{ r_libre_group }}"
  when: r_libre_dir_collect_log_details.stat.exists != true