---
- name: "install_services : Enable specific packages repositories"
  yum:
    name:
    - epel-release
  become: yes
#- name: "install_services : Remove PyYAML installed via package manager"
#  yum:
#    name:
#    - PyYAML
#    state: absent
#  become: yes
- name: "install_services : Ensure system dependencies packages are installed"
  yum:
    name:
    - jq
    - bind-utils
    - bash-completion
    - python-pip
  become: yes
- name: "install_services : Install and force upgrade pip packages"
  pip:
    name: "{{ pipname }}"
    state: forcereinstall
    extra_args: --upgrade
  loop:
    - pip
    - Jinja2
    - yq
  loop_control:
    loop_var: pipname
    label: "{{ pipname }}"
  become: yes
- name: "install_services : Ensure application dependencies packages are installed"
  yum:
    name:
    - git
    - ansible
    - docker
  become: yes
  
- name: "install_services : Add another bin dir to $PATH."
  copy:
    dest: /etc/profile.d/custom-path.sh
    content: 'PATH=$PATH:~/.local/bin'
- name: "install_services : Create boto configuration in /etc/boto.cfg"
  copy:
    src: "{{ role_path }}/files/boto.cfg"
    dest: "/etc/boto.cfg"
    mode: 0775
- name: "install_services : Ensure docker service is running"
  systemd:
    name: docker
    state: started
