---
- name: "config : manual : Configure of the session ID"
  pause:
   prompt: "What is your session ID ?"
  register: sessionID
  delegate_to: localhost
  when: libre_session is undefined and session_id is undefined
- name: "config : manual : Register session_id fact"
  set_fact:
    session_id: "{{ sessionID.user_input }}"
  when: libre_session is undefined and sessionID.user_input is defined
- name: "config : manual : Session ID doesn't match a good number"
  fail: msg="You must give a good Session ID"
  when: libre_session is undefined and session_id|default('')|string == ""
- name: "config : manual : Configure of the course ID"
  pause:
   prompt: "What is your course ID ?"
  register: courseID
  delegate_to: localhost
  when: libre_session is undefined and course_id is undefined
- name: "config : manual : Register course_id fact"
  set_fact:
    course_id: "{{ courseID.user_input }}"
  when: libre_session is undefined and courseID.user_input is defined
- name: "config : manual : Course ID doesn't match a good id"
  fail: msg="You must give a good course ID"
  when: libre_session is undefined and course_id|default('')|string == ""
- name: "config : manual : Generate session config file {{ r_session_dir_conf }}/{{ r_session_config_file }}"
  template:
    src: ../templates/libre-session-manual.j2
    dest: "{{ r_session_dir_conf }}/{{ r_session_config_file }}"
    mode: 0664
    owner: "{{ r_session_user }}"
    group: "{{ r_session_group }}"
  become: yes
