---
- name: "load : config : Get session configuration {{ config_libre.directory.conf }}/{{ r_session_config_file }} file details"
  stat:
    path: "{{ config_libre.directory.conf }}/{{ r_session_config_file }}" 
  register: r_session_conf_details
- name: "load : config : Load session configuration from {{ config_libre.directory.conf }}/{{ r_session_config_file }}"
  set_fact:
    libre_session: "{{ lookup('file', config_libre.directory.conf + '/' + r_session_config_file) | from_json | default({students: [{ id : 'INST', name : 'instructor', email : 'libre@startx.fr', workstation : '0' }]}) }}"
  when: r_session_conf_details.stat.exists
- name: "load : config : Get {{ config_libre.directory.conf }} directory details"
  stat:
    path: "{{ config_libre.directory.conf }}"
  register: r_libre_dir_conf_details