---
- name: "provision : Start infrastructure configuration"
  include_tasks: "config.yml"
  when: r_infra_conf_details.stat.exists != true or libre_infra is undefined
- name: "provision : Provision {{ libre_infra.type }} infrastructure"
  include_tasks: "{{ libre_infra.type }}/provision.yml"

# Install post-tasks
- name: "provision : Start post-provision checks"
  include_tasks: "provision-post.yml"
  when: libre_infra.type == 'self'
