## LIBRE Training-Repo role tasks
---
- name: "Action {{ r_do }} in repository role is supported"
  assert:
    msg: "Action {{ r_do }} in repository role is not supported"
    that: r_do in ['load','status','install','update','uninstall']
- name: "{{ r_do }} repository environement"
  include_tasks: "{{ r_do }}.yml"
  when: r_do in ['load','status','install','update','uninstall']
