---
# Uninstall tasks
- name: "uninstall : Remove local course repository {{ config_repository.local }}"
  file:
    state: absent
    path: "{{ config_repository.local }}"
  when: 
    - r_repository_details.stat.exists == true
    - r_repository_uninstall_deep == true
- name: "uninstall : Start LIBRE uninstall"
  include_role:
    name: libre
    tasks_from: uninstall
  when: r_repository_uninstall_deep == true
- name: "uninstall : Get previous report data"
  set_fact:
    previous_report: "{{ lookup('file', r_libre_tmp + '/' + r_libre_tmpfile) | default('') }}"
  delegate_to: localhost
  become: no
- name: "uninstall : Generate LIBRE report at {{ r_libre_tmp }}/{{ r_libre_tmpfile }}"
  template:
    src: libre_report-uninstall.j2
    dest: "{{ r_libre_tmp }}/{{ r_libre_tmpfile }}"
    mode: 0664
  delegate_to: localhost
  become: no
