## LIBRE role meta informations
---
galaxy_info:
  author: Startx dev
  description: LIBRE Training Toolkit - LIBRE role
  company: STARTX
  license: Apache License, Version 2.0
  min_ansible_version: 2.5
  platforms:
  - name: CentOS
    versions:
    - 7
  categories:
  - cloud
  - system
  - training
