---
# Reset post-tasks
- name: "Reset lab on local (post-tasks)"
  hosts: 'local'
  gather_facts: no
  user: root
  roles:
    - { role: lab, do: load }
    - { role: lab, do: post, lab_action: reset }