---
- name: "Post-Provision classroom infrastructure on instructor"
  hosts: 'instructor'
  gather_facts: true
  roles:
    - { role: infra, do: load, infra_type: self }
    - { role: infra, do: provision-post, infra_type: self, become: yes }

- name: "Post-Provision classroom infrastructure on workstations"
  hosts: 'workstations'
  gather_facts: true
  roles:
    - { role: student, do: load }
    - { role: student, do: install, become: yes }

