---
- name: "Post-Provision classroom infrastructure on instructor"
  hosts: 'instructor'
  gather_facts: true
  roles:
    - { role: infra, do: load, infra_type: self }
    - { role: infra, do: provision-post, infra_type: self }

- name: "Post-Provision classroom infrastructure on workstations"
  hosts: 'workstations'
  gather_facts: true
  vars:
    libre_type: "student"
    libre_verbose: false
    libre_debug: false
  roles:
    - { role: student, do: load }
    - { role: student, do: install }
    
- name: "Post-Provision classroom infrastructure on instructor"
  hosts: 'instructor'
  gather_facts: true
  roles:
    - { role: session, do: load }
  tasks:
# TODO revamp this part to create a role
#
#    - name: "install : Set hostame to workstation "
#      hostname:
#        name: workstation
#      loop: "{{ groups['workstations'] }}"
#      loop_control:
#        loop_var: server
#        label: "{{ server }}"
    - name: "install : Copy session {{ libre_session.id }} configuration to workstations"
      copy:
        src: "{{ config_libre.directory.conf }}/{{ r_session_config_file }}"
        dest: "{{ config_libre.directory.conf }}/{{ r_session_config_file }}"
      delegate_to: "{{ server }}"
      loop: "{{ groups['workstations'] }}"
      loop_control:
        loop_var: server
        label: "{{ server }}"
    - name: "install : Synchronize course {{ libre_session.course }} content to workstations"
      copy:
        src: "{{ r_session_dir_course }}/"
        dest: "{{ r_session_dir_course }}"
      delegate_to: "{{ server }}"
      delegate_facts: yes
      loop: "{{ groups['workstations'] }}"
      loop_control:
        loop_var: server
        label: "{{ server }}"
    - name: "install : provision-post : Authorize infrastructure SSH key for root"
      authorized_key:
        user: "root"
        state: present
        key: "{{ lookup('file', config_libre.directory.conf + '/infra-id_rsa.pub') }}"
      delegate_to: "{{ server }}"
      loop: "{{ groups['classroom'] }}"
      loop_control:
        loop_var: server
        label: "{{ server }}"

